---
language: generic
dist: xenial

services:
  - docker

stages:
  - test

jobs:
  include:
    - stage: test
      script:
      - docker run -v `pwd`/docs:/srv/test testthedocs/cci-linkcheck docs



