name: Lighthouse Audit
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse and ensure performance budget
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://developers.onna.com
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      # - name: Save results
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: lighthouse-results
      #     path: './lighthouse-results'
